INSERT INTO book (id, name, author, format, price) VALUES (1001,'The Adventures of Duck and Goose', 'Sir Quackalot', 'paperback', 10.99);
INSERT INTO book (id, name, author, format, price) VALUES (1002,'The Return of Duck and Goose', 'Sir Quackalot','paperback', 11.99);
INSERT INTO book (id, name, author, format, price) VALUES (1003,'More Fun with Duck and Goose', 'Sir Quackalot','paperback', 12.99);
INSERT INTO book (id, name, author, format, price)  VALUES (1004,'Duck and Goose on Holiday', 'Sir Quackalot','paperback', 11.99);
INSERT INTO book (id, name, author, format, price) VALUES (1005,'The Return of Duck and Goose', 'Sir Quackalot','hardback', 19.99);
INSERT INTO book (id, name, author, format, price) VALUES (1006,'The Adventures of Duck and Goose', 'Sir Quackalot', 'hardback', 18.99);
INSERT INTO book (id, name, author, format, price) VALUES (1007,'My Friend is a Duck', 'A. Parrot', 'paperback',14.99);
INSERT INTO book (id, name, author, format, price) VALUES (1008,'Annotated Notes on the ‘Duck and Goose’ chronicles','Prof Macaw', 'ebook', 8.99);
INSERT INTO book (id, name, author, format, price) VALUES (1009,'‘Duck and Goose’ Cheat Sheet for Students','Polly Parrot', 'ebook', 5.99);
INSERT INTO book (id, name, author, format, price) VALUES (1010,'‘Duck and Goose’: an allegory for modern times?','Bor Ing', 'hardback', 59.99);